'use strict';
const $=id=>document.getElementById(id);
let token=location.hash.slice(1)||sessionStorage.getItem('plc-token')||'';
if(token){sessionStorage.setItem('plc-token',token);history.replaceState(null,'',location.pathname);}
let project, selected={kind:'tasks',index:0}, dirty=false, latest=null, previousBusy=false, watchBuild='', activeTab='networks';
const scopeChoices=new Map();
const types=['BOOL','BYTE','INT','DINT','REAL','LREAL','TIME','STRING'];
function element(tag,attrs={},children=[]){const node=document.createElement(tag);for(const[k,v]of Object.entries(attrs)){if(k==='text')node.textContent=v;else if(k.startsWith('on'))node.addEventListener(k.slice(2),v);else if(k==='class')node.className=v;else if(k==='value')node.value=v;else if(k==='checked')node.checked=v;else node.setAttribute(k,v);}for(const child of children)node.append(child);return node;}
function button(text,fn,cls=''){return element('button',{text,class:cls,onclick:()=>{try{fn();}catch(e){notice(e.message,true);}}});}
function input(value,fn,type='text'){return element('input',{value,type,onchange:e=>{try{fn(type==='number'?Number(e.target.value):e.target.value);markDirty();}catch(err){notice(err.message,true);}}});}
function select(values,value,fn){const node=element('select');for(const item of values){const [v,label]=Array.isArray(item)?item:[item,item];node.append(element('option',{value:v,text:label}));}node.value=value;node.addEventListener('change',e=>{fn(e.target.value);});return node;}
function notice(text,error=false){$('notice').textContent=text;$('notice').classList.toggle('error',error);}
function markDirty(){dirty=true;$('editState').textContent='Unsaved changes';$('load').disabled=true;updateLive();}
async function api(action,data){const response=await fetch('/api/'+action,{method:data===undefined?'GET':'POST',headers:{'X-PLC-Token':token,'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});const result=await response.json();if(!response.ok||result.ok===false)throw Error(result.error||'Request failed');return result;}
async function save(){await api('project',{project});dirty=false;$('editState').textContent='Saved project';notice('Project saved. Compile to apply code changes.');}
async function action(name){try{if(name==='build'){await save();showTab('log');}await api(name,{});if(name==='load')notice('Program loaded in STOP. Select RUN to execute.');if(name==='run')notice('CPU is running. Online values and network status refresh automatically.');if(name==='stop')notice('CPU stopped. Process outputs are zero.');await poll();}catch(e){notice(e.message,true);}}
function currentBlock(){return project[selected.kind][selected.index];}
function blockName(block){return block.name||'OB'+block.ob;}
function showTab(tab){activeTab=tab;document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('hidden',p.id!==tab));if(tab==='project')$('projectJson').value=JSON.stringify(project,null,2);if(tab==='data')renderData();}
function choose(kind,index){selected={kind,index};renderTree();renderNetworks();showTab('networks');}
function renderTree(){const root=$('tree');root.replaceChildren();for(const[kind,label,icon]of[['tasks','ORGANIZATION BLOCKS','OB'],['blocks','PROGRAM BLOCKS','FB']]){root.append(element('div',{class:'treeGroup',text:label}));project[kind].forEach((b,i)=>{const row=button('',()=>choose(kind,i),'treeItem'+(selected.kind===kind&&selected.index===i?' active':''));row.append(element('span',{class:'blockIcon',text:b.kind==='FC'?'FC':kind==='tasks'?'OB':'FB'}),element('span',{text:blockName(b)}),element('small',{text:kind==='tasks'?(b.kind==='startup'?'startup':(b.period_ms||10)+' ms'):b.kind}));root.append(row);});}root.append(element('div',{class:'treeGroup',text:'DATA BLOCKS'}));for(const db of project.data_blocks||[])root.append(button('DB'+db.number+' · '+(db.name||'Global data'),()=>showTab('data'),'treeItem'));for(const inst of project.instances||[])root.append(button('DB'+inst.db+' · '+inst.name,()=>showTab('data'),'treeItem'));$('projectName').textContent=project.name;}
function renderNetworks(){const block=currentBlock();if(!block)return;$('blockTitle').textContent=blockName(block);$('blockDescription').textContent=selected.kind==='tasks'?({main:'Main cyclic program',cyclic:'Periodic OB with priority scheduling',startup:'Executes once on each STOP → RUN transition'}[block.kind]):(block.kind==='FB'?'Function block · state belongs to its instance DB':'Function · temporary values reset on each call');const settings=$('taskSettings');settings.replaceChildren();if(selected.kind==='tasks'){const row=element('div',{class:'settings'});for(const[key,label,def]of[['period_ms','Cycle / period (ms)',10],['priority','Priority',block.kind==='main'?1:12],['watchdog_ms','Watchdog (ms)',1000]])row.append(element('label',{text:label},[input(block[key]??def,v=>{block[key]=v;renderTree();},'number')]));settings.append(row);}
$('declarations').value=block.declarations||'';$('declarations').oninput=e=>{block.declarations=e.target.value;markDirty();};const root=$('networkList');root.replaceChildren();(block.networks||[]).forEach((net,index)=>root.append(renderNetwork(net,index,block)));updateLive();}
function renderNetwork(net,index,block){const card=element('article',{class:'network','data-index':index,'data-block':blockName(block)});const head=element('div',{class:'networkHead'});head.append(element('span',{class:'networkNumber',text:'NETWORK '+(index+1)}));const title=input(net.title||'',v=>{net.title=v;});title.className='networkTitle';head.append(title,select(['LAD','STL','SCL','C','CPP'],net.language||'SCL',lang=>{net.language=lang;if(lang==='LAD'){net.branches??=[[]];net.coils??=[];net.calls??=[];}else net.source??='';markDirty();renderNetworks();}),element('span',{class:'trace',text:'offline'}),element('select',{class:'scopeSelect hidden',onchange:e=>{scopeChoices.set(blockName(block)+':'+index,e.target.value);updateLive();}}));head.append(button('↑',()=>moveNetwork(index,-1)),button('↓',()=>moveNetwork(index,1)),button('×',()=>{block.networks.splice(index,1);markDirty();renderNetworks();}));card.append(head);
if(net.language==='LAD'){card.append(ladderSvg(net,false),ladderEditor(net));}else{if(net.language==='C'||net.language==='CPP')card.append(element('div',{class:'nativeNote',text:'Native function body · PlcContext* ctx is available · use plc_read / plc_write / PLC_TRY · return 0 on success'}));const editor=element('textarea',{class:'source',spellcheck:'false',value:net.source||'',oninput:e=>{net.source=e.target.value;markDirty();},onkeydown:e=>{if(e.key==='Tab'){e.preventDefault();const n=e.target,p=n.selectionStart,q=n.selectionEnd;n.value=n.value.slice(0,p)+'    '+n.value.slice(q);n.selectionStart=n.selectionEnd=p+4;net.source=n.value;markDirty();}}});card.append(editor);}return card;}
function moveNetwork(index,delta){const list=currentBlock().networks;const next=index+delta;if(next<0||next>=list.length)return;[list[index],list[next]]=[list[next],list[index]];markDirty();renderNetworks();}
function svgNode(tag,attrs,text){const n=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);if(text!==undefined)n.textContent=text;return n;}
function ladderSvg(net,power){const rows=net.branches?.length?net.branches:[[]],max=Math.max(1,...rows.map(r=>r.length)),outputs=[...(net.coils||[]).map(c=>({kind:'coil',...c})),...(net.calls||[]).map(c=>({kind:'call',...c}))];const width=Math.max(680,max*150+350),height=Math.max(130,rows.length*65+45,outputs.length*65+45);const svg=svgNode('svg',{viewBox:`0 0 ${width} ${height}`,class:'ladderDrawing',role:'img','aria-label':'Ladder network: parallel branches with series contacts and output coils'});const line=(x1,y1,x2,y2,cls='')=>svg.append(svgNode('line',{x1,y1,x2,y2,class:cls}));const cls=power?'powered':'';line(28,18,28,height-16,'rail '+cls);line(width-28,18,width-28,height-16,'rail '+cls);const merge=width-230;line(merge,50,merge,Math.max(rows.length,outputs.length)*65-15,cls);
rows.forEach((row,ri)=>{const y=50+ri*65;let x=28;for(let ci=0;ci<row.length;ci++){const cx=100+ci*150;line(x,y,cx-11,y,cls);line(cx-11,y-13,cx-11,y+13,cls);line(cx+11,y-13,cx+11,y+13,cls);if(row[ci].nc)line(cx-18,y+19,cx+18,y-19,cls);svg.append(svgNode('text',{x:cx,y:y-24,'text-anchor':'middle'},row[ci].tag||'contact'));x=cx+11;}line(x,y,merge,y,cls);});
if(!outputs.length)svg.append(svgNode('text',{x:width-150,y:50,'text-anchor':'middle'},'Add a coil or call'));
outputs.forEach((o,i)=>{const y=50+i*65,cx=width-115;line(merge,y,cx-24,y,cls);line(cx+24,y,width-28,y,cls);if(o.kind==='coil'){svg.append(svgNode('path',{d:`M ${cx-8} ${y-14} Q ${cx-28} ${y} ${cx-8} ${y+14} M ${cx+8} ${y-14} Q ${cx+28} ${y} ${cx+8} ${y+14}`,class:cls}));svg.append(svgNode('text',{x:cx,y:y+4,'text-anchor':'middle'},o.mode==='set'?'S':o.mode==='reset'?'R':''));svg.append(svgNode('text',{x:cx,y:y-23,'text-anchor':'middle'},o.tag||'coil'));}else{svg.append(svgNode('rect',{x:cx-60,y:y-20,width:120,height:40,rx:3,class:cls}));svg.append(svgNode('text',{x:cx,y:y+4,'text-anchor':'middle'},o.block||'FB / FC'));}});return svg;}
function ladderEditor(net){const root=element('details',{class:'ladderEditor'});root.append(element('summary',{text:'Edit contacts, parallel branches, coils and block calls'}));(net.branches||[[]]).forEach((row,ri)=>{const div=element('div',{class:'branchEdit'});div.append(element('span',{text:'Branch '+(ri+1)}));row.forEach((c,ci)=>{div.append(element('span',{class:'contactEdit'},[input(c.tag,v=>{c.tag=v;renderNetworks();}),button(c.nc?'NC':'NO',()=>{c.nc=!c.nc;markDirty();renderNetworks();}),button('×',()=>{row.splice(ci,1);markDirty();renderNetworks();})]));});div.append(button('+ Contact',()=>{row.push({tag:'DB1.Start',nc:false});markDirty();renderNetworks();}));if((net.branches||[]).length>1)div.append(button('Remove branch',()=>{net.branches.splice(ri,1);markDirty();renderNetworks();}));root.append(div);});root.append(button('+ Parallel branch',()=>{net.branches??=[];net.branches.push([]);markDirty();renderNetworks();}));(net.coils||[]).forEach((coil,i)=>{root.append(element('div',{class:'coilEdit'},[element('span',{text:'Output coil'}),input(coil.tag,v=>{coil.tag=v;renderNetworks();}),select([['coil','Direct'],['set','Set'],['reset','Reset']],coil.mode||'coil',v=>{coil.mode=v;markDirty();renderNetworks();}),button('×',()=>{net.coils.splice(i,1);markDirty();renderNetworks();})]));});root.append(button('+ Coil',()=>{net.coils??=[];net.coils.push({tag:'DB1.Run',mode:'coil'});markDirty();renderNetworks();}));root.append(element('p',{class:'hint',text:'Enabled block calls (JSON). Example: [{"block":"Motor1","inputs":{"Enable":"DB1.Run"},"outputs":{"Ready":"DB1.MotorReady"}}]'}));root.append(element('textarea',{value:JSON.stringify(net.calls||[],null,2),spellcheck:'false',onchange:e=>{try{const calls=JSON.parse(e.target.value);if(!Array.isArray(calls))throw Error('Calls must be an array');net.calls=calls;markDirty();renderNetworks();}catch(err){notice(err.message,true);}}}));return root;}
function renderData(){const root=$('dbList');root.replaceChildren();for(const db of project.data_blocks||[]){const card=element('div',{class:'dbCard'});card.append(element('h2',{text:'DB'+db.number+' · '+(db.name||'Global data')}));const table=element('table'),head=element('tr');for(const h of ['Name','Type','Byte','Bit','Initial',''])head.append(element('th',{text:h}));table.append(head);db.fields.forEach((f,i)=>{const tr=element('tr');tr.append(element('td',{},[input(f.name,v=>f.name=v)]),element('td',{},[select(types,f.type,v=>{f.type=v;f.initial=v==='BOOL'?false:v==='STRING'?'':0;markDirty();renderData();})]),element('td',{},[input(f.offset??0,v=>f.offset=v,'number')]),element('td',{},[input(f.bit??0,v=>f.bit=v,'number')]),element('td',{},[input(String(f.initial??0),v=>{f.initial=f.type==='BOOL'?v.toLowerCase()==='true'||v==='1':f.type==='STRING'?v:Number(v);})]),element('td',{},[button('×',()=>{db.fields.splice(i,1);markDirty();renderData();})]));table.append(tr);});card.append(table,button('+ Field',()=>{let off=Math.max(0,...db.fields.map(f=>(f.offset||0)+[1,1,2,4,4,8,8,256][types.indexOf(f.type)]));db.fields.push({name:'Value'+(db.fields.length+1),type:'DINT',offset:off,initial:0});markDirty();renderData();}));root.append(card);}const instances=element('div',{class:'dbCard'});instances.append(element('h2',{text:'FB instance DBs'}));for(const inst of project.instances||[])instances.append(element('p',{text:`DB${inst.db} · ${inst.name} → ${inst.type} · separate persistent state`}));instances.append(element('p',{class:'hint',text:'Compiled instance field offsets appear in Online watch after loading. VAR_TEMP and FC scratch values are not stored in an instance DB.'}));root.append(instances);}
function renderWatch(snapshot){if(!snapshot.tags)return;if(watchBuild!==snapshot.build_id){watchBuild=snapshot.build_id;$('watchRows').replaceChildren();for(const tag of snapshot.tags){const tr=element('tr',{'data-id':tag.id,'data-search':(tag.name+' '+tag.address).toLowerCase()});tr.append(element('td',{text:tag.name}),element('td',{text:tag.address||'—'}),element('td',{text:tag.type}),element('td',{class:'value',text:''}));const write=element('td',{class:'writeCell'});if(tag.type!=='STRING'&&tag.name!=='System.CycleTime'){const field=tag.type==='BOOL'?select([['0','FALSE'],['1','TRUE']],tag.value?'1':'0',()=>{}):element('input',{value:String(tag.value),'aria-label':'New value for '+tag.name});write.append(field,button('Write',async()=>{try{await api('write',{id:tag.id,value:field.value});notice('Value written once: '+tag.name);await poll();}catch(e){notice(e.message,true);}}));}tr.append(write);$('watchRows').append(tr);}}
const byId=new Map(snapshot.tags.map(t=>[String(t.id),t]));for(const tr of $('watchRows').children){const tag=byId.get(tr.dataset.id);if(tag)tr.querySelector('.value').textContent=typeof tag.value==='boolean'?(tag.value?'TRUE':'FALSE'):String(tag.value);tr.classList.toggle('hidden',!tr.dataset.search.includes($('filter').value.toLowerCase()));}
$('loadedBuild').textContent=`${snapshot.program} · Loaded build ${snapshot.build_id} · ${snapshot.tags.length} monitored values`;
const cards=element('div',{class:'diagGrid'});for(const task of snapshot.tasks||[])cards.append(element('div',{class:'diagCard'},[element('strong',{text:`${task.name} · ${task.period_us/1000} ms · priority ${task.priority}`}),element('span',{text:`Scans ${task.cycles}    Last ${task.last_us} µs`}),element('span',{text:`Max ${task.max_us} µs    Overruns ${task.overruns}`}),element('span',{text:`Missed releases ${task.missed}    Jitter ${task.jitter_us} µs`})]));$('diagnostics').replaceChildren(cards);}
function updateLive(){if(!latest||!project)return;const s=latest.runtime,b=latest.build,valid=!dirty&&b.source_matches&&b.manifest?.build_id===s.build_id;for(const card of document.querySelectorAll('.network')){const n=valid?b.manifest.networks.find(x=>x.block===card.dataset.block&&x.index===Number(card.dataset.index)+1):null;const traces=n?(s.networks||[]).filter(x=>x.id===n.id):[];const span=card.querySelector('.trace'),drop=card.querySelector('.scopeSelect'),key=card.dataset.block+':'+card.dataset.index;
const scopes=traces.map(t=>t.scope);if(drop.dataset.scopes!==JSON.stringify(scopes)){drop.replaceChildren(...scopes.map(scope=>element('option',{value:scope,text:scope})));drop.dataset.scopes=JSON.stringify(scopes);}drop.classList.toggle('hidden',scopes.length<2);const chosen=scopeChoices.get(key);if(chosen&&scopes.includes(chosen))drop.value=chosen;const trace=traces.find(t=>t.scope===drop.value)||traces[0];span.textContent=trace?`${trace.scope} · ${trace.count} visits · ${trace.power?'power ON':'power OFF'}`:valid?'not executed':'offline / code changed';span.classList.toggle('on',!!trace?.power&&s.state==='RUN');const svg=card.querySelector('.ladderDrawing');if(svg){const net=currentBlock()?.networks?.[Number(card.dataset.index)];if(net){const isOn=!!trace?.power&&s.state==='RUN';if(svg.dataset.power!==String(isOn)){const next=ladderSvg(net,isOn);next.dataset.power=String(isOn);svg.replaceWith(next);}}}}}
async function poll(){try{latest=await api('status');const s=latest.runtime,b=latest.build;$('cpuState').textContent=s.state;$('cpuState').className='state '+s.state;$('connection').textContent=s.program?'CPU · '+s.program:'Local CPU · no program loaded';$('buildLog').textContent=b.log||'No build yet.';$('buildState').textContent=b.busy?'Compiling…':b.error?'Build failed':b.ready?'Build ready · '+b.manifest.build_id:'Ready to compile';$('build').disabled=b.busy;$('load').disabled=b.busy||!b.ready||dirty||!b.source_matches||s.state==='RUN';$('run').disabled=s.state!=='STOP';$('stop').disabled=s.state!=='RUN';$('step').disabled=s.state!=='STOP';$('reset').disabled=!['STOP','FAULT'].includes(s.state);if(previousBusy&&!b.busy)notice(b.error?'Build failed: '+b.error:'Build succeeded. STOP the CPU if necessary, then Load to CPU.',!!b.error);previousBusy=b.busy;if(s.fault)notice(s.fault,true);renderWatch(s);updateLive();}catch(e){$('connection').textContent='Connection unavailable';notice(e.message,true);}}
$('save').onclick=()=>save().catch(e=>notice(e.message,true));for(const id of ['build','load','run','stop','step'])$(id).onclick=()=>action(id);$('reset').onclick=()=>{if(confirm('Reset all DB and instance values to their configured initial values?'))action('reset');};document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));$('filter').oninput=()=>latest&&renderWatch(latest.runtime);
$('addNetwork').onclick=()=>{const b=currentBlock();b.networks??=[];b.networks.push({title:'New network',language:'SCL',source:'// Write SCL here\n'});markDirty();renderNetworks();};
$('addOb').onclick=()=>{const v=prompt('OB number (1 = main, 35 = cyclic, 100 = startup):','36');if(v===null)return;const ob=Number(v);if(!Number.isInteger(ob)||ob<1||project.tasks.some(t=>t.ob===ob))return notice('Choose an unused positive OB number',true);const kind=ob===1?'main':ob===100?'startup':'cyclic';project.tasks.push({ob,kind,period_ms:100,priority:12,watchdog_ms:1000,networks:[]});markDirty();choose('tasks',project.tasks.length-1);};
$('addBlock').onclick=()=>{const name=prompt('Block name:','FB_New');if(!name)return;const kind=prompt('Block kind: FB or FC','FB')?.toUpperCase();if(!['FB','FC'].includes(kind))return;project.blocks??=[];project.blocks.push({name,kind,declarations:'VAR_INPUT\n Enable : BOOL;\nEND_VAR\nVAR_OUTPUT\n Result : BOOL;\nEND_VAR',networks:[{title:'Logic',language:'SCL',source:'Result := Enable;'}]});markDirty();choose('blocks',project.blocks.length-1);};
$('addDb').onclick=()=>{const v=prompt('DB number:','2');if(v===null)return;const number=Number(v);project.data_blocks??=[];project.data_blocks.push({number,name:'Global data',fields:[]});markDirty();renderTree();showTab('data');};
$('addInstance').onclick=()=>{const name=prompt('Instance name:','Motor2');if(!name)return;const type=prompt('FB type:',(project.blocks||[]).find(b=>b.kind==='FB')?.name||'TON');if(!type)return;const db=Number(prompt('Instance DB number:','102'));project.instances??=[];project.instances.push({name,type,db});markDirty();renderTree();renderData();};
$('applyJson').onclick=()=>{try{const p=JSON.parse($('projectJson').value);if(p.schema!==1||!Array.isArray(p.tasks)||!Array.isArray(p.blocks))throw Error('Project requires schema: 1, tasks and blocks arrays');project=p;selected={kind:'tasks',index:0};markDirty();renderTree();renderNetworks();notice('JSON applied to editor. Save and Compile to validate it.');}catch(e){notice(e.message,true);}};
$('export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(project,null,2)],{type:'application/json'}));const a=element('a',{href:url,download:'softplc-project.json'});a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
(async()=>{try{const r=await api('session');project=r.project;project.blocks??=[];selected.index=Math.max(0,project.tasks.findIndex(t=>t.ob===1));renderTree();renderNetworks();await poll();setInterval(()=>poll(),500);}catch(e){notice(e.message,true);}})();
